### PR TITLE
add slm

### PR DESCRIPTION
**Pull request by denar90**

### CODE REVIEW

**Comment by sormy** [comment]
Nice PR. Update README.md with note about new functionality, please.

**Comment by denar90** [comment]
@sormy sorry forgot about readme. Is it enough? Do you wanna me to add some example, e.g. like `jade` ?

**Comment by es128** [comment]
Don't need all these redundant tests, they're not accomplishing anything as far as exercising progeny's internals.

What we don't have now and could use for all the built-in extension settings, including a .slm version, is fixtures and tests that check different scenarios that are format-specific.

If you feel like setting up the structure for that here with .slm as the first example that would be great, but I'd also accept the PR without it if you just remove all the test copies you made.

**Comment by denar90** [comment]
@es128 thanks, I've removed copy-pasted tests. You can merge it if it's ok.

**Pull request merged**
