### PR TITLE
Progeny: Initial globs support.

### PR DESCRIPTION
**Pull request by paulmillr**
Initial impl by @shvaikalesh.

### CODE REVIEW

**Comment by es128** [comment]
Still need to add readme updates to the PR

**Comment by shvaikalesh** [comment]
Done, please see #26.

**Comment by es128** [comment]
I suppose we should bump to 1.0 when releasing this.

@paulmillr @shvaikalesh wdyt?

**Comment by shvaikalesh** [comment]
It is not breaking, so my vote goes for `0.9` on this and lets leave `1.0` for some possible API breaking stuff in the future.

**Comment by es128** [comment]
I just mean in terms of indicating stability, getting off 0.x. This has been in use out there for a long time.

I'm fine with 0.9.0 though for now. If nothing else happens here after a while we can publish as 1.0.0 with no changes.

**Comment by shvaikalesh** [comment]
I think we should add promises support before reaching `1.0`.

**Comment by es128** [comment]
LGTM. @paulmillr feel free to merge and publish if it's ready to go.

**Pull request merged**
